set_property PACKAGE_PIN AA13 [get_ports {btns_tri_i[0]}]
set_property PACKAGE_PIN AE14 [get_ports {btns_tri_i[1]}]
set_property PACKAGE_PIN AE15 [get_ports {btns_tri_i[2]}]
set_property PACKAGE_PIN AG14 [get_ports {btns_tri_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns_tri_i[*]}]

set_property PACKAGE_PIN W13	 [get_ports {leds_tri_o[0]}]
set_property PACKAGE_PIN Y12	 [get_ports {leds_tri_o[1]}]
set_property PACKAGE_PIN AA12 [get_ports {leds_tri_o[2]}]
set_property PACKAGE_PIN AB13 [get_ports {leds_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_tri_o[*]}]